-- 费用计算涉及到的系统参数
INSERT INTO `base_biz`.`param_parameter` (`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (72, 'biz', 'IsSubPurFixedFeeDiscount', '认申购业务固定费用时，是否打折', '1', '1', '认申购业务固定费用时，是否打折:0-不打折,1-打折,2-分销售商', 0, 'changrui', '2020-11-12 15:24:48', null, null)
INSERT INTO `base_biz`.`param_parameter` (`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (73, 'biz', 'MultiDisCountHandleType', '多重折扣处理方式', '1', '1', '多重折扣处理方式:0-按折上折,1-按最大折扣', 0, 'changrui', '2020-11-12 15:24:52', null, null)
INSERT INTO `base_biz`.`param_parameter` (`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (74, 'biz', 'ChooseChargeDivideLastOne', '费用分成兜底方式', '1', '1', '费用分成兜底方式:0-由管理人兜底,1-由销售商兜底', 0, 'changrui', '2020-11-12 15:24:52', null, null)



DELETE from param_parameter where param_type = 'dividend' and param_code in ('GenByShareDetail','DealType','PerformCompenSelfAccJudgeTradeAcc','WhitelistNotNeedPerformCompen','ActiveFrzShareDividNotFrz','BlacklistMustRevest','TaSharesMustRevest','FrzDividMustRevest','OpenPerformCompenByRtnRateDivided','InterEmpSharesAutoFrzUnfrz','PerformCompenOverDividNeedReduceShare','RevestDetailGenByFrzDetail','RevestCalcFee');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1124, 'dividend', 'ActiveFrzShareDividNotFrz', '分红处理时,主动冻结份额的分红款不冻结', '1', '1', '分红处理时,主动冻结份额的分红款不冻结，1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:36:41');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1125, 'dividend', 'BlacklistMustRevest', '分红处理时对于黑名单客户强制再投资', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:36:52');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1121, 'dividend', 'DealType', '分红处理方式', '0', '1', '0,1,2,3,4,5,6', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:38:43');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1127, 'dividend', 'FrzDividMustRevest', '分红有冻结时，现金红利是否强制再投资', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:37:13');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1120, 'dividend', 'GenByShareDetail', '分红按份额明细生成', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:37:17');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1129, 'dividend', 'InterEmpSharesAutoFrzUnfrz', '内部员工份额自动冻结解冻', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:37:21');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1128, 'dividend', 'OpenPerformCompenByRtnRateDivided', '开通业绩提成按收益率区间分成功能', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:37:24');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1130, 'dividend', 'PerformCompenOverDividNeedReduceShare', '分红业绩提成超出分红金额部分是否强减份额', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:37:28');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1122, 'dividend', 'PerformCompenSelfAccJudgeTradeAcc', '业绩报酬自营账户判断交易账号', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:37:30');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1131, 'dividend', 'RevestDetailGenByFrzDetail', '份额冻结生成再投资分红明细时，按照冻结明细生成', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:37:33');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1126, 'dividend', 'TaSharesMustRevest', '挂TA份额分红强制再投资', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:37:36');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1123, 'dividend', 'WhitelistNotNeedPerformCompen', '白名单投资者不提取业绩报酬功能', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:37:40');
INSERT INTO `base_biz`.`param_parameter`(`id`, `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES (1132, 'dividend', 'RevestCalcFee', '红利再投是否算费', '1', '1', '1-是，0-否', 0, 'admin', '2020-07-13 10:10:44', 'admin', '2020-11-12 14:37:40');

-- 开通内部员工减免申购赎回费用
delete from `base_biz`.`param_parameter` where param_code in ('OpenInsidePersonAvoidFee','InterestTransferShareCalFee','FailSubPurSpecialFeeMoreTaFee','DealWayOfTheManualCfmFailAndOrgCtlFail');
INSERT INTO `base_biz`.`param_parameter` ( `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES ('biz', 'OpenInsidePersonAvoidFee', '开通内部员工减免申购赎回费用', '1', '1', '开通内部员工减免申购赎回费用，0:参与优惠;1:不参与优惠;2:分基金设置,默认不参与优惠', 0, 'changrui', '2020-11-12 15:24:52', null, null);
INSERT INTO `base_biz`.`param_parameter` ( `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES ('biz', 'InterestTransferShareCalFee', '利息转份额是否需要收费', '1', '1', '利息转份额是否需要收费，0-否，1-是', 0, 'changrui', '2020-11-12 15:24:52', null, null);
INSERT INTO `base_biz`.`param_parameter` ( `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES ('biz', 'FailSubPurSpecialFeeMoreTaFee', '认申购指定费用大于TA计算结果确认失败', '1', '1', '认申购指定费用大于TA计算结果确认失败，0-否，1-是', 0, 'changrui', '2020-11-12 15:24:52', null, null);
INSERT INTO `base_biz`.`param_parameter` ( `param_type`, `param_code`, `param_name`, `param_value`, `enable_flag`, `param_explain`, `delete_flag`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES ('biz', 'DealWayOfTheManualCfmFailAndOrgCtlFail', '对于人工逐笔确认失败的及因销售商规模控制确认失败的导致的处理方式', '1', '1', '对于人工逐笔确认失败的及因销售商规模控制确认失败的导致的处理方式，0-按成立业务下发，1-按发行失败业务下发', 0, 'changrui', '2020-11-12 15:24:52', null, null);
